name: Scoreboard
version: BETA 1.2
description: The awesome free scoreboard manager
main: nl.rien_bijl.ScoreBoard.Super
author: HelloitsRien
commands:
   scoreboard:
      description: Scoreboard main command
      aliases: [cb, scoreb, sboard, board]